# Site settings
title: Vu and Tracy's Wedding page
email: vuclemson@domain.com
description: This page contains information about our wedding
baseurl: /
url: "http://vuandtracy.com" # the base hostname & protocol for your site
twitter_username: vuclemson
github_username:  vuclemson

# Build settings
markdown: kramdown
